# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  staging.pltrelliscool.tk:
    site_hosts:
      - canonical: www.staging.pltrelliscool.tk
#        redirects:
#          - www.example.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: pilourerolle@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    repo: git@github.com:Plrerolle/pltrelliscool.tk.git
    repo_subtree_path: site
    branch: master
    env:
      wp_home: http://www.staging.pltrelliscool.tk
      wp_siteurl: http://www.staging.pltrelliscool.tk/wp
      wp_env: staging
      db_name: staging_pltrelliscool_db
      db_user: admin
    deploy_keep_releases: 5
